### ISSUE TITLE
2.0.1 : issue with XML and json parsing

### ISSUE THREAD

**Issue by isaguimiot** [dependency-check/dependency-check-sonar-plugin#210]
**Describe the bug**
I have dependency check reports generated with version 5.2.4, that used to be parsed without issue in 1.2.6, but fail with 2.0.1

**To Reproduce**
I attach the 2 reports files (xml and json), just try to launch a sonarqube audit and you will get the errors
[dependency-check-report.zip](https://github.com/dependency-check/dependency-check-sonar-plugin/files/4110527/dependency-check-report.zip)

**Current behavior**
With json parsing :
```15:10:48.653 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Problem with JSON-Report-Mapping
org.sonar.dependencycheck.parser.ReportParserException: Problem with JSON-Report-Mapping
        at org.sonar.dependencycheck.parser.JsonReportParserHelper.parse(JsonReportParserHelper.java:44)
        at org.sonar.dependencycheck.DependencyCheckSensor.parseAnalysis(DependencyCheckSensor.java:63)
        at org.sonar.dependencycheck.DependencyCheckSensor.execute(DependencyCheckSensor.java:121)

Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "suppressedVulnerabilities" (class org.sonar.dependencycheck.parser.element.Dependency), not marked as ignorable (9 known properties: "filePath", "evidenceCollected", "sha1", "fileName", "vulnerabilities", "vulnerabilityIds", "packages", "md5", "identifiers"])
 at [Source: sun.nio.ch.ChannelInputStream@58548e30; line: 1, column: 38291] (through reference chain: org.sonar.dependencycheck.parser.element.Analysis["dependencies"]->java.util.ArrayList[0]->org.sonar.dependencycheck.parser.element.Dependency["suppressedVulnerabilities"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)
```
and with the XML parsing : 
```15:10:48.655 [INFO] [org.sonarqube.gradle.SonarQubeTask] Using XML-Reportparser
15:10:48.889 [WARN] [org.sonarqube.gradle.SonarQubeTask] XML-Analysis aborted due to: Mandatory elements are missing. Plugin is compatible to https://jeremylong.github.io/DependencyCheck/dependency-check.2.2.xsd
15:10:48.892 [DEBUG] [org.sonarqube.gradle.SonarQubeTask] Problem with XML-Report-Mapping
org.sonar.dependencycheck.parser.ReportParserException: Problem with XML-Report-Mapping
        at org.sonar.dependencycheck.parser.XMLReportParserHelper.parse(XMLReportParserHelper.java:45)
        at org.sonar.dependencycheck.DependencyCheckSensor.parseAnalysis(DependencyCheckSensor.java:77)
        at org.sonar.dependencycheck.DependencyCheckSensor.execute(DependencyCheckSensor.java:121)

Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "notes" (class org.sonar.dependencycheck.parser.element.Identifier), not marked as ignorable (2 known properties: "confidence", "id"])
 at [Source: sun.nio.ch.ChannelInputStream@7adde193; line: 1, column: 51136] (through reference chain: org.sonar.dependencycheck.parser.element.Analysis["dependencies"]->java.util.ArrayList[1]->org.sonar.dependencycheck.parser.element.Dependency["identifiers"]->org.sonar.dependencycheck.parser.element.Identifier["notes"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1093)
```

**Versions (please complete the following information):**

-   dependency-check : 5.2.4
-   sonarqube : 7.9.1
-   dependency-check-sonar-plugin : 2.0.1 (error) 1.2.6 (works fine)

**Additional context**
java / gradle project, gradle sonar plugin 2.8

**Comment by Reamer** [comment]
Hi @isaguimiot,
thanks for the great bug report. It was very easy to reproduce the bug. Thanks for this.
Please compile the plugin on [branch parser_exception_210](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/parser_exception_210) yourself and give me feedback if it fix your issue.

**Comment by isaguimiot** [comment]
Hi @Reamer ! Thanks for your quick fix, I just tested it and now it works fine ! Will we have a 2.0.2 release soon ? :)
