### ISSUE TITLE
JSON-Report-Mapping failing due to missing md5 property in dependencies

### ISSUE THREAD

**Issue by AAUJoin** [dependency-check/dependency-check-sonar-plugin#220]
Hi,

We were generating a dependency check report for our Node.JS project via [dependency-check/azuredevops](https://github.com/dependency-check/azuredevops) with JSON & HTML formats enabled.
The report location was found by the sonarqube analyzer, but the analysis was aborted due to:

```09:42:51.009 INFO: Using JSON-Reportparser
09:42:51.245 WARN: JSON-Analysis aborted
09:42:51.245 DEBUG: Problem with JSON-Report-Mapping
org.sonar.dependencycheck.parser.ReportParserException: Problem with JSON-Report-Mapping
	at org.sonar.dependencycheck.parser.JsonReportParserHelper.parse(JsonReportParserHelper.java:44)
	at org.sonar.dependencycheck.DependencyCheckSensor.parseAnalysis(DependencyCheckSensor.java:63)
	at org.sonar.dependencycheck.DependencyCheckSensor.execute(DependencyCheckSensor.java:121)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ProjectSensorsExecutor.execute(ProjectSensorsExecutor.java:49)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:354)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Missing required creator property 'md5' (index 2)
at [Source: sun.nio.ch.ChannelInputStream@522c0bd9; line: 1, column: 2121] (through reference chain: org.sonar.dependencycheck.parser.element.Analysis["dependencies"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1247)
	at com.fasterxml.jackson.databind.deser.impl.PropertyValueBuffer._findMissing(PropertyValueBuffer.java:192)
	at com.fasterxml.jackson.databind.deser.impl.PropertyValueBuffer.getParameters(PropertyValueBuffer.java:159)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:471)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:401)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2924)
	at org.sonar.dependencycheck.parser.JsonReportParserHelper.parse(JsonReportParserHelper.java:40)
	... 24 common frames omitted
```

The stacktrace is pointing towards a missing md5 property in the dependencies array. Checking our `dependency-check-report.json`, there is indeed no such property defined in any one of the listed dependencies.

```json
{
  "reportSchema": "1.1",
  "scanInfo": {
    "engineVersion": "5.2.1",
    "dataSource": [
      {
        "name": "NVD CVE Checked",
        "timestamp": "2020-02-26T09:41:57"
      },
      {
        "name": "NVD CVE Modified",
        "timestamp": "2020-02-26T06:01:16"
      },
      {
        "name": "VersionCheckOn",
        "timestamp": "2020-02-26T03:03:53"
      }
    ]
  },
  "projectInfo": {
    "name": "<project-name>",
    "reportDate": "2020-02-26T09:42:16.079Z",
    "credits": {
      "NVD": "This report contains data retrieved from the National Vulnerability Database: http://nvd.nist.gov",
      "NPM": "This report may contain data retrieved from the NPM Public Advisories: https://www.npmjs.com/advisories",
      "RETIREJS": "This report may contain data retrieved from the RetireJS community: https://retirejs.github.io/retire.js/",
      "OSSINDEX": "This report may contain data retrieved from the Sonatype OSS Index: https://ossindex.sonatype.org"
    }
  },
  "dependencies": [
    {
      "isVirtual": true,
      "fileName": "qs",
      "filePath": "<project-path>\\package-lock.json?qs",
      "projectReferences": [
        "<project-name>: transitive"
      ],
      "relatedDependencies": [
        {
          "isVirtual": true,
          "filePath": "<project-path>\\package-lock.json?qs",
          "packageIds": [
            {
              "id": "pkg:npm/qs"
            }
          ]
        },
        {
          "isVirtual": true,
          "filePath": "<project-path>\\package-lock.json?qs",
          "packageIds": [
            {
              "id": "pkg:npm/qs"
            }
          ]
        }
      ],
      "evidenceCollected": {
        "vendorEvidence": [
          {
            "type": "vendor",
            "confidence": "HIGH",
            "source": "package.json",
            "name": "name",
            "value": "qs"
          }
        ],
        "productEvidence": [
          {
            "type": "product",
            "confidence": "HIGHEST",
            "source": "package.json",
            "name": "name",
            "value": "qs"
          }
        ],
        "versionEvidence": []
      },
      "packages": [
        {
          "id": "pkg:npm/qs",
          "confidence": "HIGHEST"
        }
      ],
      "vulnerabilities": [
        {
          "source": "NPM",
          "name": "28",
          "severity": "high",
          "cwes": [],
          "description": "Versions prior to 1.0.0 of `qs` are affected by a denial of service vulnerability that results from excessive recursion in parsing a deeply nested JSON string.\n\n",
          "notes": "",
          "references": [
            {
              "source": "Advisory 28: Denial-of-Service Extended Event Loop Blocking",
              "name": ""
            }
          ],
          "vulnerableSoftware": [
            {
              "software": {
                "id": "cpe:2.3:a:*:qs:\\<1.0.0:*:*:*:*:*:*:*"
              }
            }
          ]
        }
      ]
    }
  ]
}
```

The mapping exception seem to occure due to the `md5` property being marked as required in [Dependency.java#L58](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/6cbfa977b42a2bf0ff03ee4913dee9d9901c0aef/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/parser/element/Dependency.java#L58). It also looks like the next exception would occur when the dependency object is checked for the `sha1` property, as it is also not available in the report for any dependency.

I unfortunately can't really classify if this is a problem with this report analyzer being to strict regarding the availability of those hash fields or the dependency checker being unable to provide those hashes.

The only conspicuity regarding the dependency check run would be:
```
[WARN] Analyzing `<project-path>\package-lock.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
[INFO] Finished Node.js Package Analyzer (0 seconds)
```

... a warning which is correct, because we don't have an installed project in the build pipeline at the point of time where we run the dependency-check & sonarqube tasks. Could this be the reason for the missing hashes? If so, would it be possible to ignore the missing hashes in this report analyzer, as the dependency-checker seems to be able to produce a meaningful report even without an existing node_modules directory?

**Comment by Reamer** [comment]
Fixed in #230
You can compile the plugin by yourself or wait for a release.
