### ISSUE TITLE
[html] dependency-check-report not getting uploaded to SQ

### ISSUE THREAD

**Issue by shashanksinha89** [dependency-check/dependency-check-sonar-plugin#284]
**Description**

- Dependency report (html version) is getting generated properly. It can be accessed via jenkins workspace directly.

![Screen Shot 2020-10-19 at 5 15 25 PM](https://user-images.githubusercontent.com/13620565/96457397-c6ebbb80-1230-11eb-814d-226f16494b34.png)

- Sonarqube doesn't displays the report and gives this message.

_No HTML-Report found. Please check property sonar.dependencyCheck.htmlReportPath_

**Tool Versions:**

- dependency-check-plugin - Core version 5.3.2
- SonarQube Version - Enterprise EditionVersion 8.4.1

Relevant Jenkins log to highlight command for report generation and it's processing via SonarQube as well.

```
/opt/jenkins/tools/org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstallation/dependency-check-5.3.2/bin/dependency-check.sh --disableNodeAudit -s /opt/jenkins/workspace/SEC/SonarQube/UC/MonthlyScan/xxxxx/
[INFO] Checking for updates
[INFO] Skipping NVD check since last check was within 4 hours.
[INFO] Skipping RetireJS update since last update was within 24 hours.
[INFO] Check for updates complete (397 ms)
[INFO] 

Dependency-Check is an open source tool performing a best effort analysis of 3rd party dependencies; false positives and false negatives may exist in the analysis performed by the tool. Use of the tool and the reporting provided constitutes acceptance for use in an AS IS condition, and there are NO warranties, implied or otherwise, with regard to the analysis or its use. Any use of the tool and the reporting provided is at the user’s risk. In no event shall the copyright holder or OWASP be held liable for any damages whatsoever arising out of or in connection with the use of this tool, the analysis performed, or the resulting report.


[INFO] Analysis Started
[INFO] Finished File Name Analyzer (0 seconds)
[WARN] Using only the OSS Index Analyzer with Node.js can result in many false positives - please enable the Node Audit Analyzer.
[WARN] Analyzing `/opt/jenkins/workspace/SEC/SonarQube/UC/MonthlyScan/<REPO>/package-lock.json` - however, the node_modules directory does not exist. Please run `npm install` prior to running dependency-check
[INFO] Finished Node.js Package Analyzer (0 seconds)
[INFO] Finished Dependency Merging Analyzer (0 seconds)
[INFO] Finished Version Filter Analyzer (0 seconds)
[INFO] Finished Hint Analyzer (0 seconds)
[INFO] Created CPE Index (5 seconds)
[INFO] Finished CPE Analyzer (6 seconds)
[INFO] Finished False Positive Analyzer (0 seconds)
[INFO] Finished NVD CVE Analyzer (0 seconds)
[INFO] Finished RetireJS Analyzer (0 seconds)
[WARN] Unable to determine Package-URL identifiers for 16 dependencies
[INFO] Finished Sonatype OSS Index Analyzer (0 seconds)
[INFO] Finished Vulnerability Suppression Analyzer (0 seconds)
[INFO] Finished Dependency Bundling Analyzer (0 seconds)
[INFO] Analysis Complete (7 seconds)

---LOG TRUNCATED---

/opt/jenkins/tools/hudson.plugins.sonar.SonarRunnerInstallation/SQ_4.3/bin/sonar-scanner -Dsonar.host.url=https://sonarqube.xxxxx.com -Dsonar.bitbucket.branchName=master -Dsonar.scm.provider=git -Dsonar.projectKey=UC_xxxxx -Dsonar.projectName=xxxxx -Dsonar.dependencyCheck.htmlReportPath=/opt/jenkins/workspace/SEC/SonarQube/UC/MonthlyScan/xxxxx/dependency-check-report.html -Dsonar.verbose=true -X
13:01:21.481 INFO: Scanner configuration file: /opt/jenkins/tools/hudson.plugins.sonar.SonarRunnerInstallation/SQ_4.3/conf/sonar-scanner.properties
13:01:21.496 INFO: Project root configuration file: NONE
13:01:21.559 INFO: SonarScanner 4.3.0.2102
13:01:21.559 INFO: Java 1.8.0_265 Private Build (64-bit)
13:01:21.559 INFO: Linux 4.4.0-1101-aws amd64
13:01:22.142 DEBUG: keyStore is : 
13:01:22.142 DEBUG: keyStore type is : jks
13:01:22.142 DEBUG: keyStore provider is : 
13:01:22.142 DEBUG: init keystore
13:01:22.144 DEBUG: init keymanager of type SunX509
13:01:22.504 DEBUG: Create: /opt/jenkins/.sonar/cache
13:01:22.508 INFO: User cache: /opt/jenkins/.sonar/cache
13:01:22.508 DEBUG: Create: /opt/jenkins/.sonar/cache/_tmp
13:01:22.513 DEBUG: Extract sonar-scanner-api-batch in temp...
13:01:22.528 DEBUG: Get bootstrap index...
13:01:22.529 DEBUG: Download: https://sonarqube.xxxxx.com/batch/index
13:01:23.084 DEBUG: Get bootstrap completed
13:01:23.104 DEBUG: Create isolated classloader...
13:01:23.123 DEBUG: Start temp cleaning...
13:01:23.175 DEBUG: Temp cleaning done
13:01:23.179 INFO: Scanner configuration file: /opt/jenkins/tools/hudson.plugins.sonar.SonarRunnerInstallation/SQ_4.3/conf/sonar-scanner.properties
13:01:23.179 INFO: Project root configuration file: NONE
13:01:23.182 DEBUG: Execution getVersion
13:01:23.203 INFO: Analyzing on SonarQube server 8.4.1
13:01:23.205 INFO: Default locale: "en_US", source code encoding: "UTF-8" (analysis is platform dependent)
13:01:23.206 DEBUG: Work directory: /opt/jenkins/workspace/SEC/SonarQube/UC/MonthlyScan/xxxxx/.scannerwork
13:01:23.208 DEBUG: Execution execute
13:01:23.745 WARN: SonarScanner will require Java 11 to run starting in SonarQube 8.x
13:01:23.747 DEBUG: Enterprise 8.4.1.35646
13:01:24.115 INFO: Load global settings
13:01:24.369 DEBUG: GET 200 https://sonarqube.xxxxx.com/api/settings/values.protobuf | time=251ms
13:01:24.458 INFO: Load global settings (done) | time=344ms
13:01:24.475 INFO: Server id: 750CFA35-AXHtEHXWZZ03BkLhZg_i
13:01:24.496 INFO: User cache: /opt/jenkins/.sonar/cache
13:01:24.509 INFO: Load/download plugins
13:01:24.510 INFO: Load plugins index
13:01:24.532 DEBUG: GET 200 https://sonarqube.xxxxx.com/api/plugins/installed | time=22ms
13:01:24.615 INFO: Load plugins index (done) | time=105ms
13:01:24.851 INFO: Load/download plugins (done) | time=342ms
13:01:25.078 DEBUG: Plugins:
13:01:25.078 DEBUG:   * Dependency-Check 2.0.5 (dependencycheck)


----LOG TRUNCATED----

13:01:59.364 INFO: Upload Dependency-Check HTML-Report
13:01:59.367 INFO: Process Dependency-Check report (done) | time=12ms
13:01:59.367 INFO: Sensor Dependency-Check [dependencycheck] (done) | time=12ms
13:01:59.367 INFO: Sensor Zero Coverage Sensor
13:01:59.385 INFO: Sensor Zero Coverage Sensor (done) | time=18ms
13:01:59.399 INFO: SCM Publisher SCM provider for this project is: git

---LOG TRUNCATED---

13:01:59.664 INFO: Load New Code definition
13:01:59.688 DEBUG: GET 200 https://sonarqube.xxxxx.com/api/new_code_periods/show.protobuf?project=UC_xxxxx&branch=master | time=24ms
13:01:59.690 INFO: Load New Code definition (done) | time=26ms
13:01:59.865 INFO: Analysis report generated in 212ms, dir size=559 KB
13:02:00.011 INFO: Analysis report compressed in 145ms, zip size=185 KB
13:02:00.011 INFO: Analysis report generated in /opt/jenkins/workspace/SEC/SonarQube/UC/MonthlyScan/xxxxx/.scannerwork/scanner-report
13:02:00.011 DEBUG: Upload report
13:02:00.069 DEBUG: POST 200 https://sonarqube.xxxxx.com/api/ce/submit?projectKey=UC_xxxxx&projectName=xxxxx | time=57ms
13:02:00.072 INFO: Analysis report uploaded in 61ms
13:02:00.074 DEBUG: Report metadata written to /opt/jenkins/workspace/SEC/SonarQube/UC/MonthlyScan/xxxxx/.scannerwork/report-task.txt
13:02:00.074 INFO: ANALYSIS SUCCESSFUL, you can browse https://sonarqube.xxxxx.com/dashboard?id=UC_xxxxx
13:02:00.074 INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
13:02:00.074 INFO: More about the report processing at https://sonarqube..com/api/ce/task?id=AXVA88lyJam_EoqvL5zA
13:02:00.078 DEBUG: Post-jobs : 
13:02:00.333 DEBUG: stylelint-bridge server will shutdown
13:02:00.341 INFO: Analysis total time: 35.067 s
13:02:00.347 INFO: ------------------------------------------------------------------------
13:02:00.347 INFO: EXECUTION SUCCESS
13:02:00.347 INFO: ------------------------------------------------------------------------
13:02:00.347 INFO: Total time: 38.961s
13:02:00.531 INFO: Final Memory: 24M/436M
13:02:00.531 INFO: ------------------------------------------------------------------------
```

Note: This was working fine with SQ version 8.3

**Comment by Reamer** [comment]
The following line indicates that the HTML report has been uploaded to SonarQube.
```
13:01:59.364 INFO: Upload Dependency-Check HTML-Report
```

Let me check this

**Comment by Reamer** [comment]
Why do I not see the following message in your log output?
```
No HTML-Report found. Please check property sonar.dependencyCheck.htmlReportPath
```
Please run sonar-scanner in debug mode (`-X`) to get more output.

**Comment by shashanksinha89** [comment]
Because HTML was generated properly. Refer to this [gist](https://gist.github.com/shashanksinha89/32a08f87098267c930ee5da380b4f626) for detailed log.

```
13:01:59.355 INFO: Sensor Dependency-Check [dependencycheck]
13:01:59.355 INFO: Process Dependency-Check report
13:01:59.357 INFO: Using JSON-Reportparser
13:01:59.358 INFO: Dependency-Check JSON report does not exists. Please check property sonar.dependencyCheck.jsonReportPath:/opt/jenkins/workspace/SEC/SonarQube/UC/MonthlyScan/xxxxxx/${WORKSPACE}/dependency-check-report.json
13:01:59.358 INFO: JSON-Analysis skipped/aborted due to missing report file
13:01:59.361 DEBUG: JSON-Dependency-Check report does not exist.
java.io.FileNotFoundException: JSON-Dependency-Check report does not exist.
	at org.sonar.dependencycheck.report.JsonReportFile.getJsonReport(JsonReportFile.java:37)
	at org.sonar.dependencycheck.DependencyCheckSensor.parseAnalysis(DependencyCheckSensor.java:70)
	at org.sonar.dependencycheck.DependencyCheckSensor.execute(DependencyCheckSensor.java:150)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ProjectSensorsExecutor.execute(ProjectSensorsExecutor.java:49)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:356)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

13:01:59.361 INFO: Using XML-Reportparser
13:01:59.362 INFO: Dependency-Check XML report does not exists. Please check property sonar.dependencyCheck.xmlReportPath:/opt/jenkins/workspace/SEC/SonarQube/UC/MonthlyScan/xxxxxx/${WORKSPACE}/dependency-check-report.xml
13:01:59.362 INFO: XML-Analysis skipped/aborted due to missing report file
13:01:59.362 DEBUG: XML-Dependency-Check report does not exist.
java.io.FileNotFoundException: XML-Dependency-Check report does not exist.
	at org.sonar.dependencycheck.report.XmlReportFile.getXmlReport(XmlReportFile.java:37)
	at org.sonar.dependencycheck.DependencyCheckSensor.parseAnalysis(DependencyCheckSensor.java:84)
	at org.sonar.dependencycheck.DependencyCheckSensor.execute(DependencyCheckSensor.java:150)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ProjectSensorsExecutor.execute(ProjectSensorsExecutor.java:49)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:356)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

13:01:59.364 INFO: Upload Dependency-Check HTML-Report
13:01:59.367 INFO: Process Dependency-Check report (done) | time=12ms
13:01:59.367 INFO: Sensor Dependency-Check [dependencycheck] (done) | time=12ms
13:01:59.367 INFO: Sensor Zero Coverage Sensor
13:01:59.385 INFO: Sensor Zero Coverage Sensor (done) | time=18ms
13:01:59.399 INFO: SCM Publisher SCM provider for this project is: git
13:01:59.401 INFO: SCM Publisher 1 source file to be analyzed
```

**Comment by shashanksinha89** [comment]
Also @Reamer in the screenshot attached in the description you can notice the `HTML-Report`.

**Comment by Reamer** [comment]
Hi @shashanksinha89,
I can't reproduce your issue with sonarqube 7.9 LTS and sonarqube 8.5.
As mentioned, `INFO: Upload Dependency-Check HTML-Report`([Sourcecode](https://github.com/dependency-check/dependency-check-sonar-plugin/blob/e1b992767d2aa375fe664c35c8f75d2eddeabeab/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/DependencyCheckSensor.java#L103-L105)) is only printed when the HTML report is uploaded.

Please check your SonarQube server log. Maybe you have a similar problem as in #175

**Comment by shashanksinha89** [comment]
Ok, let me go through the logs. Also HTML report size is approx. 150 KB only.

**Comment by Reamer** [comment]
I will close this issue if there is no update in the next four weeks.

**Comment by jithine** [comment]
Seeing same issue with SonarQube 8.5 for html report. Not seeing any errors in sonarqube server logs. Attaching sonar-scanner output with debug logs grepped for `Dependency`
[dependency.txt](https://github.com/dependency-check/dependency-check-sonar-plugin/files/5740463/dependency.txt)

**Comment by Reamer** [comment]
Maybe this is a browser problem. Which browser do you use?
I use Firefox and Chromium for my tests.

**Comment by vladkras** [comment]
Did you set 
`sonar.dependencyCheck.htmlReportPath=dependency-check-report.html`
in your sonar properties?

**Comment by Reamer** [comment]
No reaction from the author, so I am closing this issue.
